# Generated by Django 4.2 on 2023-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/avatar.jpg', upload_to='img/avatar/%Y/%m/%d'),
        ),
    ]
