# Generated by Django 4.2 on 2023-04-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_address',
            field=models.CharField(default='Place Holder', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(default='Place Holder', max_length=500),
        ),
    ]
