# Generated by Django 4.2 on 2023-04-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile_shop_address_profile_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shop_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
