# Generated by Django 4.2 on 2023-04-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_profile_shop_address_alter_profile_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_barber',
            field=models.BooleanField(default=False),
        ),
    ]
