# Generated by Django 4.2 on 2023-04-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_profile_client_photo_profile_shop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_barber',
            field=models.BooleanField(null=True),
        ),
    ]
