# Generated by Django 4.2 on 2023-04-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile_is_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_barber',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
